### ISSUE TITLE
TZNames.GetAbbreviationsForTimeZone returns wrong short name in french for America_Eastern

### ISSUE THREAD

**Issue by msavaria** [mattjohnsonpint/TimeZoneNames#68]
The short name for daylight saving time returned is `HEE` (as per de data in the data.json.gz file) but this is incorrect

```
"America_Eastern": {​​​​​​​
    "Generic": "HE",
    "Standard": "HNE",
    "Daylight": "HEE"
}​​​​​​​,
```

It should be `HAE` for `Heure Avancée de l'Est`

**Comment by mattjohnsonpint** [comment]
This is fixed in the current version.  Thanks.
