### ISSUE TITLE
Both time zone abbreviations for 'Africa/Casablanca' should be WEST

### ISSUE THREAD

**Issue by dmytro-mazur** [mattjohnsonpint/TimeZoneNames#74]
Hi dear team,

According to https://www.timeanddate.com/time/zone/morocco/casablanca both abbreviations(Standard + Daylight) for Africa/Casablanca should be WEST. Could you please check and fix.

Thanks in advance.

**Comment by mattjohnsonpint** [comment]
Hi.  This library sources the data from the [Unicode CLDR](https://cldr.unicode.org/) project.  Data accuracy concerns should be raised there.

That said, I'm not sure that TimeAndDate is correct on this one.  The S in WEST is for Summer, not Standard.  I think it may be an error in their web site.  I've reported it to them.

Thanks.
