### ISSUE TITLE
Invalid display name for the time zone 'Volgograd Standard Time'

### ISSUE THREAD

**Issue by serhiisolodovnyk** [mattjohnsonpint/TimeZoneNames#78]
I'm having a problem with this time zone - it has a display name "(UTC+04:00) Volgograd" but 
`TZConvert.GetTimeZoneInfo("Volgograd Standard Time)` returns +3:00 time shift:
![image](https://user-images.githubusercontent.com/70412527/163586405-15684bd6-01c6-4198-87c6-68e703f26388.png)

When I was researching - I noticed that in Volgograd the official time zone is +3:00.
https://www.zeitverschiebung.net/en/timezone/europe--volgograd

 So I guess it is better to rename this time zone.

refreshed `data.json` file:
https://drive.google.com/file/d/1JWM2EMTyaa0UfuOQ2JTbkNZyesKK_HtZ/view?usp=sharing

in GZ archive:
https://drive.google.com/file/d/14pj_XDFpGftjEM33HbLwyxoRjMPdkqlK/view?usp=sharing

**Comment by mattjohnsonpint** [comment]
This was fixed in 6.0.0
