### ISSUE TITLE
Missing display name for America/Fort_Wayne,Antarctica/Troll

### ISSUE THREAD

**Issue by Jerome2606** [mattjohnsonpint/TimeZoneNames#79]
Hello,

I actually miss "en-US" display name for these two Iana codes:
America/Fort_Wayne and Antarctica/Troll

Would it be possible to add it ?

Version: 5.0.1

Thank you

**Comment by mattjohnsonpint** [comment]
`Antarctica/Troll` is un-mappable - it has no Windows equivalent (it's the only one).  So there's no Windows display name for it.

`America/Fort_Wayne` should work, as it's an alias to `America/Indiana/Indianapolis` (or `America/Indianapolis` by CLDR) and maps to `US Eastern Standard Time`.  It should have the Windows display name `(UTC-05:00) Indiana (East)`.  Does it not work for you?

**Comment by mattjohnsonpint** [comment]
This was fixed in 6.0.0.  Thanks
