### ISSUE TITLE
New Windows localized timezone names

### ISSUE THREAD

**Issue by tomkludy** [mattjohnsonpint/TimeZoneNames#82]
I am the author of https://github.com/tomkludy/TimeZoneWindowsResourceExtractor.  I simplified and automated the VM preparation for running the tool based on much simpler language pack installers on Win11, and I generated a new version of the tzinfo.json file, which you can find here: 

https://github.com/tomkludy/TimeZoneWindowsResourceExtractor/blob/master/TZResScraper/tzinfo.json

There have been a few minor TZ name changes made by Microsoft since the last time this file was updated, and there are also now 5 new translations available.

I see that you use a different format in data.json.gz but you may want to update to take advantage of these new strings.

**Comment by mattjohnsonpint** [comment]
Hi Tom!  👋   Hope you're doing well!

Thanks for the update.  I've got a few other updates pending for this project also, so I'll pull that in soon.

Many thanks!

**Comment by mattjohnsonpint** [comment]
This was done in 6.0.0.  Thanks!
