### ISSUE TITLE
Method Not Found Exception 'TimeZoneConverter.TZConvert.WindowsToIana(string, string)' after Updating TimeZoneConverter to 6.0.0 and calling TZNames.GetAbbreviationsForTimeZone()

### ISSUE THREAD

**Issue by arex388** [mattjohnsonpint/TimeZoneNames#83]
I was updating my [library](https://github.com/arex388/Arex388.TimeZones) to TimeZoneConverter 6.0.0, but when calling into `TZNames.GetAbbreviationsForTimeZone()` after the update, a method not found exception is thrown:

> Method not found: 'System.String TimeZoneConverter.TZConvert.WindowsToIana(System.String, System.String)'.
>
>    at TimeZoneNames.TZNames.GetNames(String timeZoneId, String languageKey, Boolean abbreviations)
>   at TimeZoneNames.TZNames.GetAbbreviationsForTimeZone(String timeZoneId, String languageCode)
>   at Arex388.TimeZones.TimeZones.<>c__DisplayClass0_0.<GetTimeZonesCollection>b__1(DateTimeZone _)
>   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
>   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
>   at LINQPad.Extensions.Dump[T](T o, String description, Nullable`1 depth, Nullable`1 collapseTo, Boolean toDataGrid, String exclude, String include, Nullable`1 alpha, Boolean noTotals, Nullable`1 repeatHeadersAt, Boolean includePrivate)
>   at LINQPad.Extensions.Dump[T](T o)
>   at UserQuery.Main(), line 2

I'm assuming TimeZoneNames needs to be updated with the latest TimeZoneConverter?

**Comment by mattjohnsonpint** [comment]
Thanks. I will take a look asap.

**Comment by mattjohnsonpint** [comment]
Hi.  I've fixed the problem in TimeZoneConverter and republished that as 6.0.1.  If you update, it should work with TimeZoneNames fine now.

I do have other updates coming for TimeZoneNames at some point, but this seemed a faster way to fix the issue.

Thanks.

**Comment by arex388** [comment]
Thank you!
