### ISSUE TITLE
Incorrect Abbreviation for Atlantic Daylight Time in french (fr-CA)

### ISSUE THREAD

**Issue by JimmyJonesJr** [mattjohnsonpint/TimeZoneNames#88]
When you call TZNames.GetAbbreviationsForTimeZone with "Atlantic Standard Time" and "fr-CA" the daylight abbreviation comes back as "HEA" and not "HAA" as expected (see: https://www.timeanddate.com/time/zones/adt)

**Comment by mattjohnsonpint** [comment]
Thanks, but the data isn't created or maintained through this library.  I use the data as given by the [Unicode CLDR](https://cldr.unicode.org/) project.

You can see the French names and abbreviations for this time zone here:
https://github.com/unicode-org/cldr/blob/main/common/main/fr.xml#L6912-L6923

If you wish to submit a correction to CLDR, see [their "How to contribute"](https://cldr.unicode.org/index#h.vw32p8sealpj) docs.

Thanks.
