### ISSUE TITLE
Can't get time zones for country in Xamarin Forms App

### ISSUE THREAD

**Issue by Dreadoom** [mattjohnsonpint/TimeZoneNames#95]
Reproduction steps:
put `var zones = TZNames.GetTimeZonesForCountry("AU", "en");` in any place of Xamarin Forms App
![1](https://user-images.githubusercontent.com/90913238/225117865-2425db2c-79a4-43a1-8472-cdbd660e4e0e.png)
![2](https://user-images.githubusercontent.com/90913238/225117870-ff76cdbc-0fed-4ae3-a333-d2f729e17683.jpg)

**Comment by mattjohnsonpint** [comment]
Hi again! 👋 😃 

As I showed on #94, it's working for me.  Can you provide any additional information?  The full stack trace would be very helpful.

Thanks.

**Comment by Dreadoom** [comment]
Yes, what a coincidence 👋 😃
Well, if I use library stack trace ends at this call. If I'm using your source code directly, stack trace is
![1](https://user-images.githubusercontent.com/90913238/225127144-fbfce8fb-c450-414b-a13d-dc1fb1dbb101.png)
![2](https://user-images.githubusercontent.com/90913238/225127156-a93c62d0-edae-4cfa-9397-4a937ef641f6.png)
![3](https://user-images.githubusercontent.com/90913238/225127235-a100619f-8947-44b1-b1f9-6a524e579bb1.png)
![4](https://user-images.githubusercontent.com/90913238/225127287-7d8d1683-11cb-4dda-8c10-2440ad7ff5ba.png)
![5](https://user-images.githubusercontent.com/90913238/225127317-923becc8-3aa7-4aea-bb72-55b8871cf139.png)

**Comment by Dreadoom** [comment]
The project, that I'm currently in, has a lot of "update holes". Since this is more likely `System` problem and you don't have one (and you are for sure using newly created project), I just need to update some settings. What is .NET version, targeted platform, .NET Framework and ext. for you?

**Comment by mattjohnsonpint** [comment]
The last screenshot doesn't make much sense - `KnownWIndowsTimeZoneIds.Contains` would never throw a `TimeZoneNotFoundException`.  It's just a simple dictionary lookup.

I think this is one of those cases where the debug line numbers are off by one.  The actual exception must be being thrown by the  `WindowsToIana` call below it.  Still, you wouldn't have gotten there unless somehow `KnownWindowsTimeZoneIds` actually contained IANA time zone IDs (`"Australia/Perth"`).

Either way, I think #96 will resolve the problem.  This is an optimization over your proposed PR in that it attempts to performs the conversion without raising an exception, and it only does so in the code paths where a Windows ID might be a valid input.

**Comment by Dreadoom** [comment]
I decided to create my own blank Xamarin Forms project and it all works fine. Seems like some components in my project are tweaked in a wrong way. I'm closing issue. Thanks for support!

**Comment by Dreadoom** [comment]
I found out recently, that I saw that exception because in Debugger in exception settings `System.TimeZoneNotFoundException` was checked on. When I checked that option on in blank project, I saw that exception. And, interesting enough, this exception does not crash Application for some reason.

**Comment by mattjohnsonpint** [comment]
Ahh..  That explains it.  You were only running into this in Visual Studio while catching that as a "first-chance" exception.
It happened on the call to `KnownWIndowsTimeZoneIds`, because that was when the `TZConvert` static constructor was invoked.  During that initialization, [this code](https://github.com/mattjohnsonpint/TimeZoneConverter/blob/320e439deb52039cbb38df6170ca085f53e6afd6/src/TimeZoneConverter/TZConvert.cs#L568-L576) is invoked:

```csharp
try
{
    var tzi = TimeZoneInfo.FindSystemTimeZoneById(name);
    zones.Add(tzi.Id, tzi);
}
catch
{
    // ignored
}
```

This is by design.  Normally, any exception raised by `FindSystemTimeZoneById` would be swallowed by the `catch` clause.  But in your case, you were asking VS to stop there to show you the exception anyway.

**Comment by mattjohnsonpint** [comment]
Your earlier screenshot showed this as well:

<img width="743" alt="image" src="https://user-images.githubusercontent.com/1396388/225780941-d7805034-9534-4f9f-ab2a-c5ffd5372337.png">

Normally, only the second of those two checkboxes would be checked.
