### ISSUE TITLE
Gulf Standard Time typo

### ISSUE THREAD

**Issue by TheNamelessHero** [mattjohnsonpint/TimeZoneNames#99]
Hello, 

While utilizing the TZNames.GetAbbreviationsForTimeZone(timeZone, "en-GB"), where "timeZone" is Gulf Standard Time, we return "GTS" instead of "GST" as an abbreviation. Perhaps just a typo, would be great if we can get this corrected. Not sure if the typo exists for other language codes.

**Comment by mattjohnsonpint** [comment]
Hi.  Thanks, but that data comes from CLDR, so will need to be corrected there.

There's already an issue for this here: https://unicode-org.atlassian.net/browse/CLDR-16727
